wandb_version: 1

sparseml_recipe:
  desc: null
  value: recipes/gradual_pruning/cap/10ep_fast_cap.yaml
data:
  desc: null
  value: /nvmedisk/Datasets/ILSVRC
data_dir:
  desc: null
  value: /nvmedisk/Datasets/ILSVRC
dataset:
  desc: null
  value: imagenet
train_split:
  desc: null
  value: train
val_split:
  desc: null
  value: validation
dataset_download:
  desc: null
  value: false
class_map:
  desc: null
  value: ''
model:
  desc: null
  value: deit_tiny_patch16_224
pretrained:
  desc: null
  value: true
initial_checkpoint:
  desc: null
  value: ''
resume:
  desc: null
  value: ''
no_resume_opt:
  desc: null
  value: false
num_classes:
  desc: null
  value: 1000
gp:
  desc: null
  value: null
img_size:
  desc: null
  value: 224
in_chans:
  desc: null
  value: null
input_size:
  desc: null
  value: null
crop_pct:
  desc: null
  value: 0.9
mean:
  desc: null
  value: null
std:
  desc: null
  value: null
interpolation:
  desc: null
  value: ''
batch_size:
  desc: null
  value: 256
validation_batch_size:
  desc: null
  value: 500
channels_last:
  desc: null
  value: false
fuser:
  desc: null
  value: ''
grad_accum_steps:
  desc: null
  value: 1
grad_checkpointing:
  desc: null
  value: false
fast_norm:
  desc: null
  value: false
model_kwargs:
  desc: null
  value: {}
head_init_scale:
  desc: null
  value: null
head_init_bias:
  desc: null
  value: null
torchscript:
  desc: null
  value: false
torchcompile:
  desc: null
  value: null
opt:
  desc: null
  value: adamw
opt_eps:
  desc: null
  value: 1.0e-08
opt_betas:
  desc: null
  value: null
momentum:
  desc: null
  value: 0.9
weight_decay:
  desc: null
  value: 0.005
clip_grad:
  desc: null
  value: null
clip_mode:
  desc: null
  value: norm
layer_decay:
  desc: null
  value: null
opt_kwargs:
  desc: null
  value: {}
sched:
  desc: null
  value: cosine
sched_on_updates:
  desc: null
  value: false
lr:
  desc: null
  value: 0.001
lr_base:
  desc: null
  value: 0.1
lr_base_size:
  desc: null
  value: 256
lr_base_scale:
  desc: null
  value: ''
lr_noise:
  desc: null
  value: null
lr_noise_pct:
  desc: null
  value: 0.67
lr_noise_std:
  desc: null
  value: 1.0
lr_cycle_mul:
  desc: null
  value: 1.0
lr_cycle_decay:
  desc: null
  value: 0.5
lr_cycle_limit:
  desc: null
  value: 1
lr_k_decay:
  desc: null
  value: 1.0
warmup_lr:
  desc: null
  value: 1.0e-06
min_lr:
  desc: null
  value: 1.0e-05
epochs:
  desc: null
  value: 300
epoch_repeats:
  desc: null
  value: 0.0
start_epoch:
  desc: null
  value: null
decay_milestones:
  desc: null
  value:
  - 90
  - 180
  - 270
decay_epochs:
  desc: null
  value: 1.0
warmup_epochs:
  desc: null
  value: 5
warmup_prefix:
  desc: null
  value: false
cooldown_epochs:
  desc: null
  value: 10
patience_epochs:
  desc: null
  value: 10
decay_rate:
  desc: null
  value: 0.988
no_aug:
  desc: null
  value: false
scale:
  desc: null
  value:
  - 0.08
  - 1.0
ratio:
  desc: null
  value:
  - 0.67
  - 1.5
hflip:
  desc: null
  value: 0.5
vflip:
  desc: null
  value: 0.0
color_jitter:
  desc: null
  value: 0.3
aa:
  desc: null
  value: rand-m6-mstd0.5-inc1
aug_repeats:
  desc: null
  value: 0
aug_splits:
  desc: null
  value: 0
jsd_loss:
  desc: null
  value: false
bce_loss:
  desc: null
  value: false
bce_target_thresh:
  desc: null
  value: null
reprob:
  desc: null
  value: 0.25
remode:
  desc: null
  value: pixel
recount:
  desc: null
  value: 1
resplit:
  desc: null
  value: false
mixup:
  desc: null
  value: 0.8
cutmix:
  desc: null
  value: 1.0
cutmix_minmax:
  desc: null
  value: null
mixup_prob:
  desc: null
  value: 0.2
mixup_switch_prob:
  desc: null
  value: 0.5
mixup_mode:
  desc: null
  value: batch
mixup_off_epoch:
  desc: null
  value: 0
smoothing:
  desc: null
  value: 0.1
train_interpolation:
  desc: null
  value: random
drop:
  desc: null
  value: 0.0
drop_connect:
  desc: null
  value: null
drop_path:
  desc: null
  value: 0.1
drop_block:
  desc: null
  value: null
bn_momentum:
  desc: null
  value: null
bn_eps:
  desc: null
  value: null
sync_bn:
  desc: null
  value: false
dist_bn:
  desc: null
  value: reduce
split_bn:
  desc: null
  value: false
model_ema:
  desc: null
  value: false
model_ema_force_cpu:
  desc: null
  value: false
model_ema_decay:
  desc: null
  value: 0.99992
gs_loader:
  desc: null
  value: false
gs_batch_size:
  desc: null
  value: null
gs_no_training:
  desc: null
  value: false
gs_no_aug:
  desc: null
  value: false
gs_aa:
  desc: null
  value: false
gs_distributed:
  desc: null
  value: false
seed:
  desc: null
  value: 42
worker_seeding:
  desc: null
  value: all
log_interval:
  desc: null
  value: 50
recovery_interval:
  desc: null
  value: 0
checkpoint_hist:
  desc: null
  value: 10
checkpoint_freq:
  desc: null
  value: 2
workers:
  desc: null
  value: 16
save_images:
  desc: null
  value: false
amp:
  desc: null
  value: true
amp_dtype:
  desc: null
  value: float16
amp_impl:
  desc: null
  value: native
no_ddp_bb:
  desc: null
  value: false
synchronize_step:
  desc: null
  value: false
pin_mem:
  desc: null
  value: false
no_prefetcher:
  desc: null
  value: false
output:
  desc: null
  value: output/test_run
experiment:
  desc: null
  value: test_run
eval_metric:
  desc: null
  value: top1
tta:
  desc: null
  value: 0
local_rank:
  desc: null
  value: 0
use_multi_epochs_loader:
  desc: null
  value: false
save_last:
  desc: null
  value: true
log_wandb:
  desc: null
  value: true
log_sparsity:
  desc: null
  value: true
log_param_histogram:
  desc: null
  value: true
timeout:
  desc: null
  value: 18000
apex_amp:
  desc: null
  value: false
bn_tf:
  desc: null
  value: false
jsd:
  desc: null
  value: false
native_amp:
  desc: null
  value: false
validation_batch_size_multiplier:
  desc: null
  value: 1
prefetcher:
  desc: null
  value: true
distributed:
  desc: null
  value: true
device:
  desc: null
  value: cuda:0
world_size:
  desc: null
  value: 4
rank:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1697716103.758487
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 67
      3:
      - 16
      - 23
      4: 3.9.16
      5: 0.15.8
      8:
      - 5
